package com.smokertimer.app
import android.app.*
import android.os.*
import android.content.*
import android.content.pm.PackageManager
import android.graphics.Color
import android.graphics.drawable.GradientDrawable
import android.provider.Settings
import android.view.Gravity
import android.widget.*
import java.text.SimpleDateFormat
import java.util.*

class MainActivity: Activity(){
 lateinit var count:TextView; lateinit var monthCount:TextView; lateinit var timer:TextView; lateinit var last:TextView; lateinit var status:TextView; lateinit var muteBtn:Button
 var interval=60; var end=0L; var n=0; var lastMs=0L; val h=Handler(Looper.getMainLooper())
 val prefs by lazy{getSharedPreferences("smoke",MODE_PRIVATE)}
 override fun onCreate(b:Bundle?){super.onCreate(b);val today=SimpleDateFormat("yyyyMMdd",Locale.US).format(Date());if(prefs.getString("day","")!=today){val old=prefs.getInt("count",0);val month=SimpleDateFormat("yyyyMM",Locale.US).format(Date());prefs.edit().putInt("day_"+prefs.getString("day",""),old).putInt("month_"+month,prefs.getInt("month_"+month,0)+old).putInt("count",0).putString("day",today).putLong("end",0).putLong("last",0).apply()};n=prefs.getInt("count",0);end=prefs.getLong("end",0);lastMs=prefs.getLong("last",0);interval=prefs.getInt("interval",60)
 if(Build.VERSION.SDK_INT>=31){val am=getSystemService(ALARM_SERVICE) as AlarmManager;if(!am.canScheduleExactAlarms())try{startActivity(Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM))}catch(_:Exception){}}
 if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(arrayOf("android.permission.POST_NOTIFICATIONS"),9)
 fun dp(v:Int)=(v*resources.displayMetrics.density).toInt()
 val scroll=ScrollView(this).apply{isFillViewport=true;setBackgroundColor(Color.rgb(7,20,35))}
 val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(12),dp(18),dp(18));setBackgroundColor(Color.rgb(7,20,35))}
 scroll.addView(root)
 fun tv(t:String,s:Float)=TextView(this).apply{text=t;textSize=s;setTextColor(Color.rgb(244,248,255));gravity=Gravity.CENTER}
 fun buttonBg(color:Int)=GradientDrawable().apply{setColor(color);cornerRadius=dp(16).toFloat();setStroke(dp(1),Color.rgb(45,67,96))}
 fun pretty(b:Button,color:Int=Color.rgb(22,42,68)){b.setTextColor(Color.WHITE);b.textSize=14f;b.isAllCaps=false;b.background=buttonBg(color);b.stateListAnimator=null;b.minHeight=0;b.minimumHeight=0;b.minWidth=0;b.minimumWidth=0;b.setPadding(dp(8),0,dp(8),0);b.gravity=Gravity.CENTER}
 root.addView(tv("🚭  SMOKER TIMER",22f).apply{setPadding(0,dp(6),0,dp(8))});muteBtn=Button(this).apply{text=if(prefs.getBoolean("muted",false)) "🔇 MUTED" else "🔊 SOUND";setOnClickListener{val m=!prefs.getBoolean("muted",false);prefs.edit().putBoolean("muted",m).apply();text=if(m) "🔇 MUTED" else "🔊 SOUND"}};pretty(muteBtn,Color.rgb(35,54,82));root.addView(muteBtn,LinearLayout.LayoutParams(-1,dp(44)).apply{setMargins(dp(90),dp(2),dp(90),dp(8))});val monthKey="month_"+SimpleDateFormat("yyyyMM",Locale.US).format(Date());val monthTotal=prefs.getInt(monthKey,0)+n;monthCount=tv("This month  •  "+monthTotal+" cigarettes",13f);root.addView(monthCount);count=tv(n.toString()+" cigarettes today",21f).apply{setPadding(0,dp(3),0,dp(8))};root.addView(count);timer=tv("READY",38f);timer.background=GradientDrawable().apply{setColor(Color.rgb(0,83,86));cornerRadius=dp(18).toFloat();setStroke(dp(1),Color.rgb(120,210,210))};root.addView(timer,LinearLayout.LayoutParams(-1,dp(108)).apply{setMargins(0,dp(8),0,dp(8))});last=tv(if(lastMs>0)"Last cigarette  •  "+SimpleDateFormat("HH:mm",Locale.getDefault()).format(Date(lastMs)) else "Last cigarette  •  —",13f).apply{setPadding(0,dp(2),0,dp(8))};root.addView(last)
 root.addView(Button(this).apply{text="🚬  I SMOKED";textSize=18f;setOnClickListener{smoked()};pretty(this,Color.rgb(24,103,245))},LinearLayout.LayoutParams(-1,dp(58)).apply{setMargins(0,dp(6),0,dp(6))})
 root.addView(Button(this).apply{text="◷  LOG EARLIER";pretty(this);setOnClickListener{val cal=Calendar.getInstance();TimePickerDialog(this@MainActivity,{_,hh,mm->val t=Calendar.getInstance().apply{set(Calendar.HOUR_OF_DAY,hh);set(Calendar.MINUTE,mm);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)}.timeInMillis;if(t<=System.currentTimeMillis()){n++;lastMs=t;end=t+interval*60000L;val dk=SimpleDateFormat("yyyyMMdd",Locale.US).format(Date(t));val tk="times_"+dk;val oldTimes=prefs.getString(tk,"")?:"";prefs.edit().putInt("count",n).putInt("day_"+dk,n).putString(tk,if(oldTimes.isEmpty())t.toString() else oldTimes+","+t).putLong("last",t).putLong("end",end).apply();count.text=n.toString()+" cigarettes today";monthCount.text="This month: "+(prefs.getInt("month_"+SimpleDateFormat("yyyyMM",Locale.US).format(Date()),0)+n)+" cigarettes";last.text="Last cigarette  •  "+SimpleDateFormat("HH:mm",Locale.getDefault()).format(Date(t));if(end>System.currentTimeMillis())schedule();status.text="✓ Earlier cigarette logged"}else Toast.makeText(this@MainActivity,"Choose an earlier time",Toast.LENGTH_SHORT).show()},cal.get(Calendar.HOUR_OF_DAY),cal.get(Calendar.MINUTE),true).show()}},LinearLayout.LayoutParams(-1,dp(52)).apply{setMargins(0,dp(2),0,dp(8))})
 root.addView(tv("CHOOSE INTERVAL",12f).apply{setPadding(0,dp(8),0,dp(5))});val row=LinearLayout(this);listOf(30,45,60,90).forEach{minutes->row.addView(Button(this).apply{text=minutes.toString()+"M";pretty(this,if(interval==minutes)Color.rgb(24,103,245) else Color.rgb(22,42,68));setOnClickListener{interval=minutes;val now=System.currentTimeMillis();end=now+minutes.toLong()*60000L;prefs.edit().putInt("interval",minutes).putLong("end",end).apply();schedule();timer.text=String.format(Locale.US,"%02d:00",minutes);status.text="✓ "+minutes+" minute timer started"}},LinearLayout.LayoutParams(0,dp(50),1f).apply{setMargins(dp(2),0,dp(2),0)})};root.addView(row)
 val extras=LinearLayout(this)
 extras.addView(Button(this).apply{text="◴  +5 MIN";pretty(this);setOnClickListener{if(end>0){end+=5*60000L;prefs.edit().putLong("end",end).apply();schedule();status.text="Nice! +5 minutes 💪"}else Toast.makeText(this@MainActivity,"Log a cigarette first",Toast.LENGTH_SHORT).show()}},LinearLayout.LayoutParams(0,dp(52),1f).apply{setMargins(dp(2),dp(4),dp(2),0)})
 extras.addView(Button(this).apply{text="📅  HISTORY";pretty(this,Color.rgb(79,42,139));setOnClickListener{val fmt=SimpleDateFormat("yyyyMMdd",Locale.US);val label=SimpleDateFormat("EEE dd MMM",Locale.getDefault());val clock=SimpleDateFormat("HH:mm",Locale.getDefault());val cal=Calendar.getInstance();val lines=mutableListOf<String>();for(i in 0..30){val key=fmt.format(cal.time);val raw=prefs.getString("times_"+key,"")?:"";val times=raw.split(",").mapNotNull{it.toLongOrNull()}.sorted();val v=if(i==0)n else prefs.getInt("day_"+key,-1);if(v>=0){var best=0L;for(x in 1 until times.size)best=maxOf(best,times[x]-times[x-1]);val gap=if(best>0)"  ⭐ Best gap "+(best/3600000)+"h "+((best/60000)%60)+"m" else "";val detail=if(times.isNotEmpty())"\n"+times.mapIndexed{idx,tm->"   🚬 "+(idx+1)+"   •   "+clock.format(Date(tm))}.joinToString("\n") else "";lines.add("━━━━━━━━━━━━━━━━\n"+label.format(cal.time)+"   •   "+v+" cigarettes"+gap+detail)};cal.add(Calendar.DAY_OF_YEAR,-1)};AlertDialog.Builder(this@MainActivity).setTitle("📅 Smoking History").setMessage(if(lines.isEmpty())"No history yet" else lines.joinToString("\n\n")).setPositiveButton("CLOSE",null).show()}},LinearLayout.LayoutParams(0,dp(52),1f).apply{setMargins(dp(2),dp(4),dp(2),0)})
 root.addView(extras)
 val actions=LinearLayout(this);actions.addView(Button(this).apply{text="↶  UNDO";pretty(this);setOnClickListener{if(n>0)n--;end=0;lastMs=0;(getSystemService(ALARM_SERVICE) as AlarmManager).cancel(PendingIntent.getBroadcast(this@MainActivity,7,Intent(this@MainActivity,AlarmReceiver::class.java),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE));prefs.edit().putInt("count",n).putLong("end",0).putLong("last",0).apply();count.text=n.toString()+" cigarettes today";last.text="Last cigarette  •  —"}},LinearLayout.LayoutParams(0,dp(52),1f).apply{setMargins(dp(2),dp(4),dp(2),0)});actions.addView(Button(this).apply{text="☀  NEW DAY";pretty(this,Color.rgb(151,40,55));setOnClickListener{n=0;end=0;lastMs=0;prefs.edit().putInt("count",0).putLong("end",0).putLong("last",0).apply();count.text="0 cigarettes today";last.text="Last cigarette  •  —";status.text="New day started"}},LinearLayout.LayoutParams(0,dp(52),1f).apply{setMargins(dp(2),dp(4),dp(2),0)});root.addView(actions)
status=tv("Ready",12f).apply{setPadding(0,dp(10),0,dp(4))};root.addView(status);setContentView(scroll);tick()}
 fun smoked(){n++;val now=System.currentTimeMillis();end=now+interval*60000L;val dk=SimpleDateFormat("yyyyMMdd",Locale.US).format(Date());val tk="times_"+dk;val oldTimes=prefs.getString(tk,"")?:"";prefs.edit().putInt("count",n).putInt("day_"+dk,n).putString(tk,if(oldTimes.isEmpty())now.toString() else oldTimes+","+now).putLong("end",end).putLong("last",now).apply();count.text=n.toString()+" cigarettes today";monthCount.text="This month: "+(prefs.getInt("month_"+SimpleDateFormat("yyyyMM",Locale.US).format(Date()),0)+n)+" cigarettes";last.text="Last cigarette  •  "+SimpleDateFormat("HH:mm",Locale.getDefault()).format(Date(now));schedule();status.text="✓ Logged"}
 fun schedule(){val am=getSystemService(ALARM_SERVICE) as AlarmManager;val pi=PendingIntent.getBroadcast(this,7,Intent(this,AlarmReceiver::class.java),PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);try{if(Build.VERSION.SDK_INT>=31&&am.canScheduleExactAlarms())am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,end,pi) else am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,end,pi)}catch(e:Exception){am.set(AlarmManager.RTC_WAKEUP,end,pi)}}
 fun tick(){val d=end-System.currentTimeMillis();timer.text=if(end==0L)"READY" else if(d<=0)"🔔 NOW" else String.format(Locale.US,"%02d:%02d",d/60000,(d/1000)%60);h.postDelayed({tick()},1000)}
}